



create DATABASE inlibrarymanagement;


use inlibrarymanagement;


CREATE TABLE BOOKS (
    ID BIGINT  PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(255),
    AUTHOR VARCHAR(255),
    GENRE VARCHAR(100),
    PUBLISHEDYEAR VARCHAR(50),
    AVAILABILITY BIT,
    DELETED BIT,
    CREATEDON TIMESTAMP,
    UPDATEDON TIMESTAMP
);

CREATE TABLE MEMBERS (
    ID BIGINT  PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255)  NOT NULL,
    PHONE VARCHAR(15),
    MEMBERSHIPDATE TIMESTAMP,
    CREATEDON TIMESTAMP ,
    UPDATEDON TIMESTAMP ,
    DELETED BOOLEAN
 );



CREATE TABLE BOOK_TRANSACTIONS (
    ID BIGINT  PRIMARY KEY AUTO_INCREMENT,
    MEMBERID BIGINT NOT NULL,
    BOOKID BIGINT NOT NULL,
    TRANSACTIONDATE TIMESTAMP,
    STATUS enum('BORROWED','RETURNED'),
    CREATEDON TIMESTAMP,
    CONSTRAINT FK_MEMBER FOREIGN KEY (MEMBERID) REFERENCES MEMBERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_BOOK FOREIGN KEY (BOOKID) REFERENCES BOOKS(ID) ON DELETE CASCADE
);





